recaptcha {
    // These keys are generated by the ReCaptcha service
    //localhost
    // www.wellmia.com
    //publicKey = "6LdJr8ESAAAAAIL_-5z6e71PSD-4_nPZvfFZsBv4"
    //privateKey = "6LdJr8ESAAAAABf-UyXLfJ_3XdGRrJHNh4coKFvn"

    //wellmia.appspot.com
    publicKey = "6Lfl78ASAAAAAFRCyDvJ9NwoCiMt-gWu0ctOAxAW"
    privateKey = "6Lfl78ASAAAAAAiUySqNmY7Z2U0FJd-sLJJtnpET "

	// Include the noscript tags in the generated captcha
	includeNoScript = true
}

mailhide {
    // Generated by the Mailhide service
    publicKey = ""
    privateKey = ""
}

environments {
  development {
    recaptcha {
      // These keys are generated by the ReCaptcha service
      //localhost
      publicKey = "6LfO7sASAAAAAJNBpeJ-Zf_DTnlAUT6RGFbiiy8p"
      privateKey = "6LfO7sASAAAAAEE8AS0uIgrx2B7RO2Weahgxgyp7"

      //remote dev server
      //publicKey = "6LdtAsQSAAAAAJFk54ZPezsKrbL_Ttc2Rmd7zJ67"
      //privateKey = "6LdtAsQSAAAAANOaDJ5yl41OlqFdpyxEC8tArML1"



      // Set to false to disable the display of captcha
      enabled = true

      // Communicate using HTTPS
      useSecureAPI = false
    }
  }
  production {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = true

      // Communicate using HTTPS
      useSecureAPI = false

      // These keys are generated by the ReCaptcha service
      // Wellmia keys (should override localhost settings)
      //publicKey = "6LdJr8ESAAAAAIL_-5z6e71PSD-4_nPZvfFZsBv4"
      //privateKey = "6LdJr8ESAAAAABf-UyXLfJ_3XdGRrJHNh4coKFvn"


      //wellmia.appspot.com
      publicKey = "6Lfl78ASAAAAAFRCyDvJ9NwoCiMt-gWu0ctOAxAW"
      privateKey = "6Lfl78ASAAAAAAiUySqNmY7Z2U0FJd-sLJJtnpET"
    }
  }
}