recaptcha {
    // These keys are generated by the ReCaptcha service
    //localhost
      publicKey = "6LdJr8ESAAAAAIL_-5z6e71PSD-4_nPZvfFZsBv4"
      privateKey = "6LdJr8ESAAAAABf-UyXLfJ_3XdGRrJHNh4coKFvn"

	// Include the noscript tags in the generated captcha
	includeNoScript = true
}

mailhide {
    // Generated by the Mailhide service
    publicKey = ""
    privateKey = ""
}

environments {
  development {
    recaptcha {
      // These keys are generated by the ReCaptcha service
      //localhost
      publicKey = "6LfO7sASAAAAAJNBpeJ-Zf_DTnlAUT6RGFbiiy8p"
      privateKey = "6LfO7sASAAAAAEE8AS0uIgrx2B7RO2Weahgxgyp7"

      // Set to false to disable the display of captcha
      enabled = true

      // Communicate using HTTPS
      useSecureAPI = false
    }
  }
  production {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = true

      // Communicate using HTTPS
      useSecureAPI = false

      // These keys are generated by the ReCaptcha service
      // Wellmia keys (should override localhost settings)
      publicKey = "6LdJr8ESAAAAAIL_-5z6e71PSD-4_nPZvfFZsBv4"
      privateKey = "6LdJr8ESAAAAABf-UyXLfJ_3XdGRrJHNh4coKFvn"
    }
  }
}